---
kind: pipeline
name: windows-1809
platform:
  os: windows
  arch: amd64
  version: 1809
# Currently have to define "depth" as otherwise clone fails at
# https://github.com/drone/drone-git/blob/39d233b3d9eccc68e66508a06a725a2567f33143/windows/clone-tag.ps1#L12
clone:
  depth: 20
steps:
  - name: build
    pull: always
    image: rancher/dapper:v0.5.8
    commands:
      - "docker build -f Dockerfile.windows --build-arg WINDOWS_VERSION=1809 ."
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - push
        - pull_request
        - tag
  - name: docker-publish
    image: plugins/docker
    settings:
      build_args:
        - "WINDOWS_VERSION=1809"
        - "ARCH=amd64"
        - "VERSION=${DRONE_TAG}"
      custom_dns: 1.1.1.1
      dockerfile: Dockerfile.windows
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: "rancher/fluent-bit"
      tag: "${DRONE_TAG}-windows-1809"
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - tag
      ref:
        - refs/heads/master
        - refs/tags/*
volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine
trigger:
  event:
    exclude:
      - promote

---
kind: pipeline
name: windows-ltsc2022
platform:
  os: windows
  arch: amd64
  version: 2022
# remove this and use upstream images when https://github.com/drone/drone-git/pull/25 is merged
clone:
  disable: true
steps:
  - name: clone
    image: rancher/drone-images:git-amd64-ltsc2022
    settings:
      depth: 20
  - name: build
    pull: always
    image: rancher/dapper:v0.5.8
    commands:
      - "docker build -f Dockerfile.windows --build-arg WINDOWS_VERSION=ltsc2022 ."
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - push
        - pull_request
        - tag
  - name: docker-publish
    image: rancher/drone-images:docker-amd64-ltsc2022
    settings:
      build_args:
        - "WINDOWS_VERSION=ltsc2022"
        - "ARCH=amd64"
        - "VERSION=${DRONE_TAG}"
      custom_dns: 1.1.1.1
      dockerfile: Dockerfile.windows
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: "rancher/fluent-bit"
      tag: "${DRONE_TAG}-windows-ltsc2022"
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - tag
      ref:
        - refs/heads/master
        - refs/tags/*
volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine
trigger:
  event:
    exclude:
      - promote

---
kind: pipeline
name: manifest
platform:
  os: linux
  arch: amd64
steps:
  - name: push-manifest
    image: plugins/manifest
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      spec: manifest.tmpl
    when:
      instance:
        include:
          - drone-publish.rancher.io
      event:
        - tag
trigger:
    event:
      exclude:
        - promote
depends_on:
  - windows-1809
  - windows-ltsc2022
