name: CI on Releasing Tag

on:
  push:
    tags:
      - "*"

env:
  IMAGE: rancher/fluent-bit

jobs:
  build-windows:
    strategy:
      matrix:
        include:
          - NANOSERVER_VERSION: 1809
            TAG_SUFFIX: windows-1809-amd64
            RUNNER: windows-2019
          - NANOSERVER_VERSION: ltsc2022
            TAG_SUFFIX: windows-ltsc2022-amd64
            RUNNER: windows-2022
    runs-on: ${{ matrix.RUNNER }}
    permissions:
      contents: read
      id-token: write # needed for the Vault authentication
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fix the not-a-git-repository issue
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Set environment variables
        run: |
          "ARCH=amd64" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Load secrets from Vault
        uses: rancher-eio/read-vault-secrets@main
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials username | DOCKER_USERNAME ;
            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials password | DOCKER_PASSWORD

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker image build `
          -f Dockerfile.windows `
          --build-arg WINDOWS_VERSION=${{ matrix.NANOSERVER_VERSION }} `
          --build-arg ARCH=amd64 ``
          --build-arg VERSION=${{ github.ref_name }} `
          -t ${{ env.IMAGE }}:${{ github.ref_name }}-${{ matrix.TAG_SUFFIX }} . 
          
          docker push ${{ env.IMAGE }}:${{ github.ref_name }}-${{ matrix.TAG_SUFFIX }}

  create-docker-manifest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # needed for the Vault authentication
    needs: [ build-windows ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Load secrets from Vault
        uses: rancher-eio/read-vault-secrets@main
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials username | DOCKER_USERNAME ;
            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials password | DOCKER_PASSWORD

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create Docker manifest
        run: |
          echo "creating the manifest list that contains only Windows tags to preserve the os.version metadata"
          docker manifest create ${{ env.IMAGE }}:${{ github.ref_name }} \
              ${{ env.IMAGE }}:${{ github.ref_name }}-windows-1809-amd64 \
              ${{ env.IMAGE }}:${{ github.ref_name }}-windows-ltsc2022-amd64 
          docker manifest push ${{ env.IMAGE }}:${{ github.ref_name }} 

      - name: Inspect image
        run: docker buildx imagetools inspect ${{ env.IMAGE }}:${{ github.ref_name }}
