name: Deploy on Releasing Tag

on:
  push:
    tags:
      - "*"

env:
  IMAGE: rancher/fluent-bit

jobs:
  create-docker-manifest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Load secrets from Vault
        uses: rancher-eio/read-vault-secrets@0da85151ad1f19ed7986c41587e45aac1ace74b6 # v3
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials username | DOCKER_USERNAME ;
            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials password | DOCKER_PASSWORD

      - name: Login to Docker Hub
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - name: Create Docker manifest
        run: |
          echo "creating the manifest list that contains only Windows tags to preserve the os.version metadata"
          docker manifest create ${{ env.IMAGE }}:${{ github.ref_name }} \
              ${{ env.IMAGE }}:windows-2019-${{ github.ref_name }}-amd64 \
              ${{ env.IMAGE }}:windows-2022-${{ github.ref_name }}-amd64
          docker manifest push ${{ env.IMAGE }}:${{ github.ref_name }}

      - name: Inspect image
        run: docker buildx imagetools inspect ${{ env.IMAGE }}:${{ github.ref_name }}
